### ISSUE TITLE
The Stackable Helm Operators can only be deployed once

### ISSUE THREAD

**Issue by Svane20** [jakobhviid/BigDataCourseExercises#40]
The Stackable Helm Operators to run HDFS can only be deployed in a single namespace and hence only once, as each operator creates a ClusterRole and ClusterRoleBinding to the defined namespace. 

Additionally, operators lack the option to configure the default IP address since it is expecting 127.0.0.1, where we are using a custom IP address, hence resulting in the required pods never being created. 

@anderslaunerbaek We need to have a chat about this

**Comment by anderslaunerbaek** [comment]
Yes. The solution is to use helm charts or plain manifest files instead. It works in lecture 3 and vi have to keep that in mind for lecture 4, 5, and 7.
